### ISSUE TITLE
Training Chinese

### ISSUE THREAD

**Issue by fuchao01** [intersun/LightningDOT#3]
How can I use my Chinese data for training?

**Comment by intersun** [comment]
Hi fuchao,

For Chinese data, the pre-trained checkpoint released in this repo won't be **directly** useful in my opinion because
(1) the model is initialized with bert-base, which is trained by English corpus (Wiki and book corpus).
(2) the pre-trained text-image pair are in English.
(3) the fine-tuned dataset are also in English only.

Based on what we did, I would suggest you could
1. Train the model by yourself, which will take lots of efforts
    (1) initialize the text encoder by using Chinese BERT
    (2) pre-trained by large amount of text-image pairs (text in Chinese)
    (3) fine-tune on your downstream task(s)

2. Or similar to what we did in our multi-lingual experiments, translate the Chinese query into English, then apply our model to retrieve. Based on our experiments, it could achieve reasonably good results. 

Thanks!

Siqi
